cask_args appdir: "/Applications"
# tap "homebrew/core"
# tap "homebrew/bundle"
# tap "homebrew/cask"
# tap "homebrew/cask-versions"
# tap "homebrew/services"
# tap "homebrew/cask-fonts"
# tap "homebrew/command-not-found"

# basic
brew "git"
brew "svn"
brew "zsh"
brew "vim"
brew "antigen"
# brew "fvm"
# brew "openjdk@8"
# brew "openjdk@11"
# brew "openjdk@17"
brew "exa"
brew "ack"
brew "trash"

# cask "scroll-reverser"
cask "alfred"
cask "cheatsheet"
cask "spectacle"
# cask "google-chrome"
cask "visual-studio-code"
# cask "android-studio"
cask "iterm2"
cask "miniconda"

tap "homebrew/cask-fonts"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
# cask "font-fira-code"

# cask "appcleaner"  


